env:
  MANIFEST: https://github.com/PixelOS-AOSP/manifest.git
  MANIFEST_BRANCH: fourteen
  DEVICE: RMX1821
  OEM: realme
  DT_LINK: https://github.com/realme3-devs/android_device_realme_RMX1821.git -b PixelOS
  DT_PATH: device/$OEM/$DEVICE
  VT_LINK: https://github.com/realme3-devs/android_vendor_realme_rmx1821.git -b 13
  VT_PATH: vendor/$OEM/$DEVICE
  KT_LINK: https://github.com/realme3-devs/android_kernel_realme_RMX1821.git -b PixelOS
  KT_PATH: kernel/$OEM/$DEVICE
  LUNCH_COMBO: lunch aosp_RMX1821-user
  TARGET: bacon
  OUTPUT: PixelOS*.zip

  # Not Recommended to Change
  SYNC_PATH: $HOME/work # Do NOT use "~". Use $HOME instead.
  CCACHE_SIZE: 30G
  CCACHE_DIR: $HOME/work/.ccache
  J_VAL: 16

  # Cirrus Specific Vars (Do *NOT* Change)
  CIRRUS_SHELL: bash

task:
  name: "PixelOS Builds"
  timeout_in: 2h
  container:
    image: apon77/aosp:cirrus
    cpu: 8
    memory: 32G

  Storage_Checker:
    - df -h
    - lsblk
    - ls -l -a -h

  Sync_script:
    - bash sync.sh

  Build_script:
    - bash build.sh

  Upload_script:
    - export TIMEOUT=43200 # Download Link Timeout (in Minutes)
    - bash upload.sh
